#!/bin/sh

mkdir -p /home/backup/.metabase

DATE=`date +"%Y-%m-%d"`
NAME="metabase-data-${DATE}"
DIR="/home/backup/.metabase/"
KEEP_DAYS=7

# Criando backup zipado caso ele não exista
if [ ! -f "${DIR}${NAME}.tar.gz" ];
then 

    scp -r cginf@cginflab.mp.intra:/home/cginf/metabase-data ${DIR}${NAME}
    cd ${DIR} && tar -cvzf ${NAME}.tar.gz -P ${NAME} && rm -rf ${NAME}

    # Apaga arquivos mais velhos que X dias
    echo "Removendo arquivos gerados há mais de $KEEP_DAYS dias"
    find ${DIR}* -mtime +${KEEP_DAYS} -delete;

    echo ${DATE} > ${DIR}/lastdate
    echo "Backup finalizado!"



fi